-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgSEPrOuJQrqAbk4Wz83Ukjq/zNBzBZqptmT5bjp0Z6KSgCgYIKoZIzj0DAQehRANCAARVNse2B5npjU8BqzzT4JEFqRQFvMHu92FdigIQSvSzF+3HXQvNf3AEJsmrGnbNgxLVyK2AgseBhodxUp/wXABk
-----END PRIVATE KEY-----